---
- name: Pull Docker Image
  hosts: ubuntu18
  remote_user: ck
  tasks:
    - name: Pull CalculatorusingDevOps Image from Docker Hub
      docker_image:
        name: docker123chetan/calculatorimage
        source: pull
